### ISSUE TITLE
Layout / Design Category Page

### ISSUE THREAD

**Issue by HerrTim** [DanielFloeter/category-archives-block#4]
First of all, awesome Plugin!
Is there a way to edit the result / output page?
If you select multiple categories and you click on the year, the page will show the first category as header. I'd like to show the year of the archive as header. Is this possible?
Is it also possible to show the full post on the result / output page?

Thanks and best regards,
Tim

**Comment by DanielFloeter** [comment]
Do you want change two things on the result / output page or more?
1.  About the header -> I'll check if it is a feature for the Category Archives Block asap.
2. About to show the full post -> Do you use a Block Theme with Full Site Editing? You can change the 'Post Excerpt' Block with a 'Post Content' Block at your 'Archive' Templates. (Because it is possibel to do with FSE Themes it wouldn't be a feature for that Category Archives Block.)
